### ISSUE TITLE
undefined method endpoint_key with example app

### ISSUE THREAD

**Issue by clebrun** [spree/endpoint_base#14]
When I try and do the example application from the readme, it won't start.

```
> ruby isolated_example.rb                                                                                                                                                        
isolated_example.rb:9:in `<class:SampleEndpoint>': undefined method `endpoint_key' for SampleEndpoint:Class (NoMethodError)
	from isolated_example.rb:4:in `<main>'
```

I have made a small app that reproduces the bug [here](https://github.com/clebrun/endpoint_key-error). This uses copy-pasted code from the README.

I've tried this on 3 different machines. They were all using rbenv though, so it could be an issue there.

**Comment by clebrun** [comment]
I think I have fixed this by setting the ENDPOINT_KEY as indicated in [here](https://github.com/spree/endpoint_base/blob/master/lib/endpoint_base/sinatra/base.rb). Is this the suggested way of doing it? I could make a pull request updating the documentation if it was.

**Comment by phstc** [comment]
Hi @clebrun 

The `ENDPOINT_KEY` is only required if you don't set the `endpoint_key`.

https://github.com/spree/endpoint_base#endpoint-1

```ruby
require "sinatra"
require "endpoint_base"

class SampleEndpoint < EndpointBase::Sinatra::Base
  # optional security check, value supplied is compared against HTTP_X_HUB_TOKEN header
  # which is included in all requests sent by the hub, header is unique per integration.
  #
  # to opt of out security check, do not include this line
  endpoint_key 'abc123'
  ...
end
```

**Comment by clebrun** [comment]
Hello @phstc

Thats what I was doing, as shown in the example I put together [here](https://github.com/spree/endpoint_base/blob/master/lib/endpoint_base/sinatra/base.rb), and it wasn't working. I'm thinking that this might have been because of an environment issue on my machine, but I have no idea how.
